# Generated by Django 6.0.7 on 2026-07-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sân')),
                ('field_type', models.CharField(choices=[('BADMINTON', 'Sân Cầu Lông'), ('FOOTBALL', 'Sân Bóng Đá')], default='BADMINTON', max_length=20, verbose_name='Loại sân')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá theo giờ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Giờ kết thúc')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã đặt thành công'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.field', verbose_name='Sân thể thao')),
            ],
        ),
    ]
