# Generated by Django 6.0.7 on 2026-08-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_code_booking_note_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Số tiền')),
                ('method', models.CharField(choices=[('CASH', 'Thanh toán tại sân'), ('BANK_TRANSFER', 'Chuyển khoản')], default='CASH', max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại')], default='PENDING', max_length=15, verbose_name='Trạng thái thanh toán')),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã giao dịch')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Đơn đặt sân')),
            ],
        ),
    ]
